// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _13_GenelTekrar2.DbContexts;

#nullable disable

namespace _13_GenelTekrar2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.Property<string>("AldigiDerslerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OgrencilerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AldigiDerslerId", "OgrencilerId");

                    b.HasIndex("OgrencilerId");

                    b.ToTable("DersOgrenci");
                });

            modelBuilder.Entity("_13_GenelTekrar2.OkulEntities.Concrete.Adres", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaddeSokak")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KapiNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OgrenciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostaKod")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("_13_GenelTekrar2.OkulEntities.Concrete.Ders", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DersAdi")
                        .IsUnique();

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            Id = "74525235-1923-4c13-81aa-1640cda1daa9",
                            CreateDate = new DateTime(2024, 5, 28, 15, 57, 25, 362, DateTimeKind.Local).AddTicks(576),
                            DersAdi = "Matematik"
                        },
                        new
                        {
                            Id = "e307264e-1305-417b-a92c-de60015f771d",
                            CreateDate = new DateTime(2024, 5, 28, 15, 57, 25, 362, DateTimeKind.Local).AddTicks(589),
                            DersAdi = "Fizik"
                        },
                        new
                        {
                            Id = "d3f778f1-89a6-4956-8ab4-fc79db623850",
                            CreateDate = new DateTime(2024, 5, 28, 15, 57, 25, 362, DateTimeKind.Local).AddTicks(606),
                            DersAdi = "Kimya"
                        },
                        new
                        {
                            Id = "452fedd2-1639-4f78-bd37-e5bbfa77491f",
                            CreateDate = new DateTime(2024, 5, 28, 15, 57, 25, 362, DateTimeKind.Local).AddTicks(610),
                            DersAdi = "Edebiyat"
                        });
                });

            modelBuilder.Entity("_13_GenelTekrar2.OkulEntities.Concrete.Ogrenci", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adsoyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("TcNo")
                        .IsUnique();

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("DersOgrenci", b =>
                {
                    b.HasOne("_13_GenelTekrar2.OkulEntities.Concrete.Ders", null)
                        .WithMany()
                        .HasForeignKey("AldigiDerslerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_13_GenelTekrar2.OkulEntities.Concrete.Ogrenci", null)
                        .WithMany()
                        .HasForeignKey("OgrencilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_13_GenelTekrar2.OkulEntities.Concrete.Adres", b =>
                {
                    b.HasOne("_13_GenelTekrar2.OkulEntities.Concrete.Ogrenci", "Ogrenci")
                        .WithMany("Adresler")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("_13_GenelTekrar2.OkulEntities.Concrete.Ogrenci", b =>
                {
                    b.Navigation("Adresler");
                });
#pragma warning restore 612, 618
        }
    }
}
