// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _8_CodeFirstTelefonRehberi;

#nullable disable

namespace _8_CodeFirstTelefonRehberi.Migrations
{
    [DbContext(typeof(SqlDbcontext))]
    [Migration("20240515141900_DeleteRuleRestrict")]
    partial class DeleteRuleRestrict
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Adres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaddeSokak")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<int>("KisiId")
                        .HasColumnType("integer");

                    b.Property<string>("Sehir")
                        .HasColumnType("text");

                    b.Property<string>("Ulke")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.ToTable("Adresler");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KisiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Telefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KisiId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KisiId");

                    b.ToTable("Telefonlar");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Adres", b =>
                {
                    b.HasOne("_8_CodeFirstTelefonRehberi.Kisi", "Kisi")
                        .WithMany("Adresler")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Email", b =>
                {
                    b.HasOne("_8_CodeFirstTelefonRehberi.Kisi", "Kisi")
                        .WithMany("Emailler")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Telefon", b =>
                {
                    b.HasOne("_8_CodeFirstTelefonRehberi.Kisi", "Kisi")
                        .WithMany("Telefonlar")
                        .HasForeignKey("KisiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kisi");
                });

            modelBuilder.Entity("_8_CodeFirstTelefonRehberi.Kisi", b =>
                {
                    b.Navigation("Adresler");

                    b.Navigation("Emailler");

                    b.Navigation("Telefonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
